var vm = new Vue({
    el: "#vue_det",
    data: {
      firstname: "Dr. Muhammad",
      lastname: "Nauman",
      htmlcontent: "<div><h1>Vue Js Template</h1></div>",
      object: {
        Site: " Geeks for Geeks ",
        Framework: " Vue ",
        Type: " Article ",
        Subject: " v-for on a <template> ",
      },
      myEmp: [
        {
          ID: "101",
          Name: "DR Ali",
          Department: "Software Engineering",
          Salary: "120000",
          Allownce: "4000",
          Rent: "3546",
         otherexpensives: "1500",
        },
        {
          ID: "102",
          Name: "Gulraiz Joiya",
          Department: "Computer Science",
          Salary: "110000",
          Allownce: "4000",
          Rent: "3543",
          otherexpensives: "1500",
        },
        {
          ID: "103",
          Name: "M Talal",
          Department: "Information Technology",
          Salary: "104000",
          Allownce: "3500",
          Rent: "3456",
          otherexpensives: "1500",
        },
        {
          ID: "104",
          Name: "MR. Daler Awan",
          Department: "Artificial Intelligence",
          Salary: "80000",
          Allownce: "4000",
          Rent: "3500",
          otherexpensives: "1500",
        },
        {
            ID: "105",
            Name: "Rafaqat Kazmi",
            Department: "Software Engineering",
            Salary: "100000",
            Allownce: "4000",
            Rent: "3500",
            otherexpensives: "1500",
          },
          {
            ID: "106",
            Name: "Shehraz  Ahmad",
            Department: "Botny",
            Salary: "120000",
            Allownce: "4000",
            Rent: "3500",
            otherexpensives: "1500",
          },
          {
            ID: "107",
            Name: "Sultan Ahmad",
            Department: "English",
            Salary: "120000",
            Allownce: "4000",
            Rent: "3500",
            otherexpensives: "1500",
          },
          {
            ID: "108",
            Name: "Zahid Mehmood",
            Department: "Zoology",
            Salary: "900000",
            Allownce: "4000",
            Rent: "3500",
            otherexpensives: "1500",
          },
          {
            ID: "109",
            Name: "Idrees Faiz",
            Department: "Software Engineering",
            Salary: "110000",
            Allownce: "4000",
            Rent: "3500",
            otherexpensives: "1500",
          },
          {
            ID: "110",
            Name: "DR Rehman Ahmad",
            Department: "Math",
            Salary: "120000",
            Allownce: "4000",
            Rent: "3500",
            otherexpensives: "1500",
          },
      ],
    },
  });